[package]
name = "uacpi"
version = "0.1.0"
edition = "2021"

[dependencies]
uacpi-sys = { path = "../uacpi-sys" }
#log = { version = "0.4", optional = true }

[features]
default = ["allocator_api", "full_acpi_hardware"]
#default = ["tables-only"]
#logging = ["log"]
reduced-hardware-only = ["uacpi-sys/reduced-hardware"]
tables-only = ["uacpi-sys/barebones-mode"]
std = ["alloc"]
allocator_api = ["alloc"]
alloc = []
aml_interpreter = []
full_acpi_hardware = ["aml_interpreter"]
